sonar.projectKey=tasklist-backend
sonar.projectName=TaskList Backend
sonar.host.url=https://sonarqube.cicd.kits.ext.educentre.fr

sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/e2e/lcov.info
sonar.sourceEncoding=UTF-8
